### PR TITLE
Added multiple "features"(?)

### PR DESCRIPTION
**Pull request by NiiWiiCamo**
Added Synology and pfSense configurations

### CODE REVIEW

**Comment by NiiWiiCamo** [comment]
added a configuration script for the inital setup as well, written in bash.

**Comment by NiiWiiCamo** [comment]
updated config script to include .htaccess file handling

**Comment by NiiWiiCamo** [comment]
Support for multiple endpoints with separate .env files as well as domain restriction via config.
Everything is backwards compatible with existing router configs, only optional URL and .env parameters added.

**Comment by fernwerker** [comment]
Why did you close the PRs?
Just didnt't get to review them and I'd love some support from people that know what they do.

**Comment by NiiWiiCamo** [comment]
created a new one, i renamed my fork branch to main… that seems to close existing PRs.

Also this is the first time i actually used php, so please don‘t think i actually know what i‘m doing xD

**Pull request closed without merging**
